// The public page reads shared data. Only authenticated editors can write it.
let cloudAdmin=false,cloudReady=false,cloudRevision=0,cloudLoading=true,cloudPending=false,cloudSending=false,cloudBlocked=false,cloudTimer;
const cloudStatus=document.getElementById('cloudStatus');
const cloudSay=(t,bad)=>{cloudStatus.textContent=t;cloudStatus.classList.toggle('cloud-error',!!bad)};
let lastSaved='',cloudProblem=0;
async function cloudRequest(body){const r=await fetch('/api/members',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json()}catch{throw Error('Chưa có dịch vụ lưu trực tuyến tại địa chỉ này.')}if(!r.ok)throw Object.assign(Error(data.error||'Không kết nối được máy chủ.'),{status:r.status});return data;}
function cloudUI(){document.body.classList.toggle('public-mode',!cloudAdmin);document.body.classList.remove('cloud-loading');$('cloudLogin').hidden=cloudAdmin;$('cloudLogout').hidden=!cloudAdmin;$('cloudLocal').hidden=!cloudAdmin;$('cloudRetry').hidden=!cloudAdmin;PUBLIC=cloudAdmin?null:{};publicUrl=location.origin+'/';render();}
async function cloudLoad(){cloudLoading=true;try{const data=await cloudRequest();cloudAdmin=data.admin;cloudReady=data.configured;cloudRevision=data.revision;members=data.members.map(m=>({...blank(),...m}));lastSaved=JSON.stringify(members);cloudPending=false;cloudBlocked=false;cloudUI();cloudSay(data.configured?(data.admin?'Đã kết nối. Bấm Lưu sau khi sửa để cập nhật website.':'Danh sách trực tuyến · tự cập nhật khi quản trị viên lưu.'):'Chưa bật lưu trực tuyến. Cần kết nối kho dữ liệu và đặt mật khẩu trên Vercel.');}catch(e){cloudSay(e.message);document.body.classList.remove('cloud-loading');}finally{cloudLoading=false}}
function queueCloudSave(){if(cloudLoading||!cloudAdmin||!cloudReady)return;if(JSON.stringify(members)===lastSaved)return;cloudPending=true;cloudSay('Có thay đổi chưa đăng lên website…');clearTimeout(cloudTimer);cloudTimer=setTimeout(flushCloud,500);}
async function flushCloud(){if(cloudSending||!cloudPending||cloudBlocked)return;const before=JSON.parse(lastSaved||'[]').length;if(before-members.length>=2&&!confirm('Website đang có '+before+' thành viên. Lưu bản này sẽ chỉ còn '+members.length+'. Vẫn lưu?')){cloudBlocked=true;cloudProblem=0;cloudSay('Đã dừng lưu vì số thành viên giảm từ '+before+' xuống '+members.length+'. Bấm Thử lưu lại nếu đúng ý, hoặc tải lại trang để bỏ thay đổi.',true);return}cloudSending=true;const snapshot=JSON.stringify(members);cloudSay('Đang lưu lên website…');try{const result=await cloudRequest({action:'save',revision:cloudRevision,members:JSON.parse(snapshot)});cloudRevision=result.revision;lastSaved=snapshot;cloudPending=JSON.stringify(members)!==snapshot;cloudSay(cloudPending?'Đang chờ lưu thay đổi tiếp theo…':'Đã lưu trực tuyến · người quét QR sẽ thấy thông tin mới.');if(typeof remindBackup==='function')remindBackup();}catch(e){cloudBlocked=true;cloudProblem=e.status||503;if(cloudProblem===401){cloudSay('CHƯA LƯU: phiên đăng nhập đã hết. Đăng nhập lại, thay đổi sẽ tự lưu tiếp. Đừng đóng trang.',true);$('cloudLoginError').textContent='Phiên đã hết. Đăng nhập lại để lưu tiếp thay đổi đang sửa.';$('cloudLoginDialog').showModal();$('cloudPassword').focus()}else cloudSay('CHƯA LƯU: '+e.message+' Bản đang sửa vẫn được giữ trên trang này, đừng đóng trang.',true);}finally{cloudSending=false;if(cloudPending&&!cloudBlocked)flushCloud()}}
const cloudRender=render;render=function(){cloudRender();queueCloudSave()};
const localPersist=persist;persist=function(){localPersist();queueCloudSave()};
$('cloudLogin').onclick=()=>{$('cloudLoginDialog').showModal();$('cloudPassword').focus()};
$('cloudLoginForm').onsubmit=async e=>{e.preventDefault();const button=$('cloudLoginSubmit');button.disabled=true;try{await cloudRequest({action:'login',password:$('cloudPassword').value});$('cloudPassword').value='';$('cloudLoginError').textContent='';$('cloudLoginDialog').close();if(cloudPending&&cloudBlocked&&cloudProblem===401){cloudAdmin=true;cloudBlocked=false;flushCloud();return}await cloudLoad()}catch(err){$('cloudLoginError').textContent=err.message}finally{button.disabled=false}};
$('cloudLoginClose').onclick=()=>{$('cloudPassword').value='';$('cloudLoginDialog').close()};
$('cloudLogout').onclick=async()=>{if(cloudPending||cloudSending){cloudSay('Còn thay đổi chưa đồng bộ. Hãy lưu thành công hoặc sao lưu trước khi đăng xuất.');return}try{await cloudRequest({action:'logout'});reset();drafts=[];renderReview();await cloudLoad()}catch(e){cloudSay(e.message)}};
$('cloudRetry').onclick=()=>{if(cloudBlocked&&cloudProblem===401){$('cloudLoginDialog').showModal();$('cloudPassword').focus();return}if(cloudBlocked&&cloudProblem===409){cloudSay('Bấm Sao lưu JSON để giữ bản đang sửa. Sau đó tải lại trang, đăng nhập và đối chiếu bản mới trước khi nhập lại thay đổi. Không tự ghi đè dữ liệu từ thiết bị khác.');return}cloudBlocked=false;flushCloud()};
$('cloudLocal').onclick=()=>{let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}if(!Array.isArray(saved)||!saved.length){cloudSay('Không có bản cũ trong trình duyệt tại địa chỉ này. Dùng Khôi phục để nhập JSON đã sao lưu từ file trên máy.');return}if(!confirm('Thay '+members.length+' thành viên đang có trên website bằng '+saved.length+' hồ sơ lưu trên trình duyệt này?\n\nTrình duyệt: '+saved.map(m=>m.name).join(', ')+'\n\nHãy Sao lưu JSON trước.'))return;members=saved;render();};
window.addEventListener('beforeunload',e=>{if(cloudPending||cloudSending){e.preventDefault();e.returnValue=''}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!cloudAdmin)cloudLoad()});
setInterval(()=>{if(!cloudAdmin&&!cloudLoading&&document.visibilityState==='visible')cloudLoad()},30000);
$('shareOpen').textContent='QR chung';$('shareOpen').onclick=()=>openQR(null);
const hint=form.querySelector('p.hint:last-child');if(hint)hint.textContent='Bấm Lưu rồi đợi trạng thái Đã lưu trực tuyến. Sao lưu JSON định kỳ để giữ bản dự phòng.';
document.querySelector('.footer').textContent='LĐBC · Danh sách trực tuyến. Thông tin công khai cập nhật khi quản trị viên lưu; ghi chú nội bộ chỉ dành cho quản trị viên.';
// Form draft: every keystroke is kept in this browser until the member is saved or the form is cleared.
const DRAFT_KEY='ldbc-form-draft';
const clearDraft=()=>{try{localStorage.removeItem(DRAFT_KEY)}catch{}};
form.addEventListener('input',()=>{if(!cloudAdmin)return;const values={};fields.forEach(k=>values[k]=form.elements[k].value);if(!Object.values(values).some(v=>v.trim()))return clearDraft();try{localStorage.setItem(DRAFT_KEY,JSON.stringify({editing,values,photo:form.elements.photo.value,at:Date.now()}))}catch{}});
const cloudReset=reset;reset=function(){cloudReset();clearDraft()};$('cancel').addEventListener('click',clearDraft);
function restoreDraft(){let d;try{d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null')}catch{}if(!d||!d.values||form.elements.name.value)return;fields.forEach(k=>form.elements[k].value=d.values[k]||'');form.elements.photo.value=d.photo||'';if(typeof updatePhotoPreview==='function')updatePhotoPreview();editing=d.editing&&members.some(m=>m.id===d.editing)?d.editing:null;$('formTitle').textContent=editing?'Chỉnh sửa thành viên (bản nháp chưa lưu)':'Thêm thành viên (bản nháp chưa lưu)';cloudSay('Đã mở lại bản nháp chưa lưu'+(d.values.name?' của “'+d.values.name+'”':'')+'. Bấm Lưu thành viên để đăng lên website.',true)}
// Server history: download any of the last 30 saved versions as a backup file for Khôi phục.
const historyButton=document.createElement('button');historyButton.id='cloudHistory';historyButton.textContent='Lịch sử bản lưu';historyButton.hidden=true;$('cloudRetry').after(historyButton);
const historyDialog=document.createElement('dialog');historyDialog.className='small-dialog';historyDialog.innerHTML='<div class="dialoghead"><h2>Lịch sử bản lưu</h2><button class="close" aria-label="Đóng">×</button></div><div class="dialogbody"><p class="hint">Mỗi lần lưu, website giữ lại bản trước đó (30 bản gần nhất). Tải bản cần lấy lại, rồi dùng Khôi phục để đưa lên.</p><div id="historyList"></div></div>';document.body.append(historyDialog);historyDialog.querySelector('.close').onclick=()=>historyDialog.close();
const fmtTime=s=>{try{return s?new Date(s).toLocaleString('vi-VN'):'không rõ thời gian'}catch{return s}};
historyButton.onclick=async()=>{const list=$('historyList');list.textContent='Đang tải…';historyDialog.showModal();try{const r=await fetch('/api/members?history=1',{credentials:'same-origin',cache:'no-store'}),data=await r.json();if(!r.ok)throw Error(data.error);list.innerHTML=data.history.length?data.history.map(h=>'<div class="row"><b>Bản #'+h.revision+' · '+esc(fmtTime(h.updatedAt))+' · '+h.count+' thành viên</b>'+esc(h.names.slice(0,8).join(', ')+(h.names.length>8?'…':''))+' <button data-rev="'+h.revision+'">Tải bản này</button></div>').join(''):'Chưa có bản lưu cũ. Lịch sử bắt đầu ghi từ lần lưu kế tiếp.'}catch(e){list.textContent=e.message||'Không tải được lịch sử.'}};
historyDialog.addEventListener('click',async e=>{const rev=e.target.dataset&&e.target.dataset.rev;if(!rev)return;try{const r=await fetch('/api/members?history=1&revision='+encodeURIComponent(rev),{credentials:'same-origin',cache:'no-store'}),data=await r.json();if(!r.ok)throw Error(data.error);download(JSON.stringify({version:1,members:data.members,publicUrl},null,2),'LDBC-ban-luu-'+data.revision+'.json','application/json')}catch(err){alert(err.message||'Không tải được bản này.')}});
const baseCloudUI=cloudUI;cloudUI=function(){baseCloudUI();historyButton.hidden=!cloudAdmin;if(cloudAdmin)setTimeout(restoreDraft)};
// Backup reminder: after every successful save, nudge the admin to download a JSON copy to this computer.
let unbackedSaves=0;
const backupReminder=document.createElement('div');backupReminder.id='backupReminder';backupReminder.hidden=true;backupReminder.innerHTML='<span></span><button type="button" class="primary">Sao lưu JSON ngay</button><button type="button" class="later">Để sau</button>';$('cloudStatus').after(backupReminder);
function remindBackup(){if(!cloudAdmin)return;unbackedSaves++;backupReminder.querySelector('span').textContent='Đã lưu '+unbackedSaves+' thay đổi lên website nhưng chưa sao lưu về máy. Hãy tải bản JSON để phòng khi mất dữ liệu.';backupReminder.hidden=false}
backupReminder.querySelector('.primary').onclick=()=>$('backup').click();backupReminder.querySelector('.later').onclick=()=>{backupReminder.hidden=true};
$('backup').addEventListener('click',()=>{unbackedSaves=0;backupReminder.hidden=true;try{localStorage.setItem('ldbc-last-backup',new Date().toISOString())}catch{}});
window.addEventListener('beforeunload',e=>{if(cloudAdmin&&unbackedSaves){e.preventDefault();e.returnValue=''}});
const cloudStyle=document.createElement('style');cloudStyle.textContent='#backupReminder{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin:8px 0;padding:10px 12px;border-radius:8px;background:#fff4d6;border:2px solid #d3ad53;color:#5a3a10;font-weight:600}#backupReminder[hidden]{display:none}#backupReminder span{flex:1 1 260px}';document.head.append(cloudStyle);cloudStyle.textContent+='#cloudStatus.cloud-error{color:#fff;background:#a3241a;padding:8px 12px;border-radius:8px;font-weight:700}#historyList .row{border-bottom:1px solid #eadfca;padding:8px 0}#historyList button{margin-top:6px}';document.head.append(cloudStyle);
if(hint)hint.textContent='Thông tin đang gõ được lưu nháp tự động trên trình duyệt. Bấm Lưu thành viên để đăng lên website, đợi trạng thái Đã lưu trực tuyến.';
cloudLoad();
