// The public page reads shared data. Only authenticated editors can write it.
let cloudAdmin=false,cloudReady=false,cloudRevision=0,cloudLoading=true,cloudPending=false,cloudSending=false,cloudBlocked=false,cloudTimer;
const cloudStatus=document.getElementById('cloudStatus');
const cloudSay=t=>{cloudStatus.textContent=t};
let lastSaved='',cloudProblem=0;
async function cloudRequest(body){const r=await fetch('/api/members',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json()}catch{throw Error('Chưa có dịch vụ lưu trực tuyến tại địa chỉ này.')}if(!r.ok)throw Object.assign(Error(data.error||'Không kết nối được máy chủ.'),{status:r.status});return data;}
function cloudUI(){document.body.classList.toggle('public-mode',!cloudAdmin);document.body.classList.remove('cloud-loading');$('cloudLogin').hidden=cloudAdmin;$('cloudLogout').hidden=!cloudAdmin;$('cloudLocal').hidden=!cloudAdmin;$('cloudRetry').hidden=!cloudAdmin;PUBLIC=cloudAdmin?null:{};publicUrl=location.origin+'/';render();}
async function cloudLoad(){cloudLoading=true;try{const data=await cloudRequest();cloudAdmin=data.admin;cloudReady=data.configured;cloudRevision=data.revision;members=data.members.map(m=>({...blank(),...m}));lastSaved=JSON.stringify(members);cloudPending=false;cloudBlocked=false;cloudUI();cloudSay(data.configured?(data.admin?'Đã kết nối. Bấm Lưu sau khi sửa để cập nhật website.':'Danh sách trực tuyến · tự cập nhật khi quản trị viên lưu.'):'Chưa bật lưu trực tuyến. Cần kết nối kho dữ liệu và đặt mật khẩu trên Vercel.');}catch(e){cloudSay(e.message);document.body.classList.remove('cloud-loading');}finally{cloudLoading=false}}
function queueCloudSave(){if(cloudLoading||!cloudAdmin||!cloudReady)return;if(JSON.stringify(members)===lastSaved)return;cloudPending=true;cloudSay('Có thay đổi chưa đăng lên website…');clearTimeout(cloudTimer);cloudTimer=setTimeout(flushCloud,500);}
async function flushCloud(){if(cloudSending||!cloudPending||cloudBlocked)return;cloudSending=true;const snapshot=JSON.stringify(members);cloudSay('Đang lưu lên website…');try{const result=await cloudRequest({action:'save',revision:cloudRevision,members:JSON.parse(snapshot)});cloudRevision=result.revision;lastSaved=snapshot;cloudPending=JSON.stringify(members)!==snapshot;cloudSay(cloudPending?'Đang chờ lưu thay đổi tiếp theo…':'Đã lưu trực tuyến · người quét QR sẽ thấy thông tin mới.');}catch(e){cloudBlocked=true;cloudProblem=e.status||503;cloudSay(e.message+' Bản đang sửa vẫn được giữ trên trang này.');}finally{cloudSending=false;if(cloudPending&&!cloudBlocked)flushCloud()}}
const cloudRender=render;render=function(){cloudRender();queueCloudSave()};
const localPersist=persist;persist=function(){localPersist();queueCloudSave()};
$('cloudLogin').onclick=()=>{$('cloudLoginDialog').showModal();$('cloudPassword').focus()};
$('cloudLoginForm').onsubmit=async e=>{e.preventDefault();const button=$('cloudLoginSubmit');button.disabled=true;try{await cloudRequest({action:'login',password:$('cloudPassword').value});$('cloudPassword').value='';$('cloudLoginDialog').close();await cloudLoad()}catch(err){$('cloudLoginError').textContent=err.message}finally{button.disabled=false}};
$('cloudLoginClose').onclick=()=>{$('cloudPassword').value='';$('cloudLoginDialog').close()};
$('cloudLogout').onclick=async()=>{if(cloudPending||cloudSending){cloudSay('Còn thay đổi chưa đồng bộ. Hãy lưu thành công hoặc sao lưu trước khi đăng xuất.');return}try{await cloudRequest({action:'logout'});reset();drafts=[];renderReview();await cloudLoad()}catch(e){cloudSay(e.message)}};
$('cloudRetry').onclick=()=>{if(cloudBlocked&&[401,409].includes(cloudProblem)){cloudSay('Bấm Sao lưu JSON để giữ bản đang sửa. Sau đó tải lại trang, đăng nhập và đối chiếu bản mới trước khi nhập lại thay đổi. Không tự ghi đè dữ liệu từ thiết bị khác.');return}cloudBlocked=false;flushCloud()};
$('cloudLocal').onclick=()=>{let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}if(!Array.isArray(saved)||!saved.length){cloudSay('Không có bản cũ trong trình duyệt tại địa chỉ này. Dùng Khôi phục để nhập JSON đã sao lưu từ file trên máy.');return}if(!confirm('Thay danh sách trực tuyến đang xem bằng '+saved.length+' hồ sơ trên trình duyệt này? Hãy kiểm tra và sao lưu trước.'))return;members=saved;render();};
window.addEventListener('beforeunload',e=>{if(cloudPending||cloudSending){e.preventDefault();e.returnValue=''}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!cloudAdmin)cloudLoad()});
setInterval(()=>{if(!cloudAdmin&&!cloudLoading&&document.visibilityState==='visible')cloudLoad()},30000);
$('shareOpen').textContent='QR chung';$('shareOpen').onclick=()=>openQR(null);
const hint=form.querySelector('p.hint:last-child');if(hint)hint.textContent='Bấm Lưu rồi đợi trạng thái Đã lưu trực tuyến. Sao lưu JSON định kỳ để giữ bản dự phòng.';
document.querySelector('.footer').textContent='LĐBC · Danh sách trực tuyến. Thông tin công khai cập nhật khi quản trị viên lưu; ghi chú nội bộ chỉ dành cho quản trị viên.';
cloudLoad();
